@startuml ПР0
left to right direction
actor Клиент
actor Банк
rectangle Банкомат{
  Клиент -- (Снятие наличных)
  Клиент -- (Проверка баланса)
  Клиент-- (Внесение наличных)
  (Снятие наличных) <- (Проверка баланса) : extends
  (Внесение наличных) <- (Проверка баланса) : extends
  Банк -- (Проверка баланса)
}
@enduml
